---
- name: remove the iis web service
  hosts: windows

  tasks:
    - name: stopped iis service
      win_feature:
        name: W3Svc
        state: stopped
    - name: remove iis
      win_service:
        name: Web-Server
        state: absent
    - name: remove iis
      win_reboot:
        state: True        

    - name: Show website Status
      debug:
        msg: IIS removido